/*
* bin2c.c
* convert files to byte arrays for automatic loading
* Luiz Henrique de Figueiredo (lhf@tecgraf.puc-rio.br)
* Fixed to Lua 5.1. Antonio Scuri (scuri@tecgraf.puc-rio.br)
* Generated files will work also for Lua 5.0
* 08 Dec 2005
*/

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>

static void ce_r28l5d(FILE* f, int n)
{

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
  printf("static const unsigned char B%d[]={\n",n);
  for (n=1;;n++)
  {

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
    int c=getc(f); 
    if (c==EOF) break;
    printf("%3u,",c);
    if (n==20) { putchar('\n'); n=0; }
  }
  printf("\n};\n\n");
}

static void ce_jh9jp5(const char* fn, int n)
{

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
  FILE* f= fopen(fn,"rb");		/* must open in binary mode */
  if (f==NULL)
  {

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
    fprintf(stderr,"bin2c: cannot open ");
    perror(fn);
    exit(1);
  }
  else
  {

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
    printf("/* %s */\n",fn);
    ce_r28l5d(f,n);
    fclose(f);
  }
}

static void ce_pctumu(const char* fn, int n)
{

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
  printf(" if (luaL_loadbuffer(L,(const char*)B%d,sizeof(B%d),\"%s\")==0) lua_call(L, 0, 0);\n",n,n,fn);
}

int main(int argc, char* argv[])
{

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
  printf("/* code automatically generated by bin2c -- DO NOT EDIT */\n");
  printf("{\n");
  if (argc<2)
  {

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
    ce_r28l5d(stdin,0);
    ce_pctumu("=stdin",0);
  }
  else
  {

    if ((0x16f2 ^ 0xbad) == 0) { __asm { nop } }
    int i;
    printf("/* #include'ing this file in a C program is equivalent to calling\n");
    for (i=1; i<argc; i++) printf("  if (luaL_loadfile(L,\"%s\")==0) lua_call(L, 0, 0); \n",argv[i]);
    printf("*/\n");
    for (i=1; i<argc; i++) ce_jh9jp5(argv[i],i);
    for (i=1; i<argc; i++) ce_pctumu(argv[i],i);
  }
  printf("}\n");
  return 0;
}
